<a href="https://colab.research.google.com/github/AnnmariyaFrancis/ICT_ML_AI/blob/main/Python_ML_Bootcamp_Jan28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

importing the dataset

In [ ]:
df=pd.read_csv('/content/Book2.csv')

In [ ]:
df.describe()

Age         salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:
df.columns

Index(['country', 'Age ', 'salary', 'purchase'], dtype='object')

In [ ]:
data=df.values

In [ ]:
df.nunique()

country     3
Age         9
salary      9
purchase    2
dtype: int64

metion inputa and output columns

In [ ]:
X=data[:,:-1]#input

In [ ]:
y=data[:,-1]#last column is not included,#output

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

Spliting into train and test datasets

In [ ]:
from sklearn.model_selection import train_test_split

input features are splitted into X_train and x_test
y is splitted into y_test and y_train


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
X_train.shape

(8, 3)

In [ ]:
X_test.shape

(2, 3)

Now we deal with the missing data

In [ ]:
from sklearn .impute import SimpleImputer#simple imputer is a class we have to create a object 

In [ ]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')#we can use strategy='constant',fill_value=0

In [ ]:
imputer.fit(X_train[:,1:3])

SimpleImputer()

In [ ]:
X_train[:,1:3]=imputer.transform(X_train[:,1:3])

In [ ]:
X_train

array([['Spain', 40.285714285714285, 52000.0],
       ['Germany', 40.0, 64714.28571428572],
       ['France', 44.0, 72000.0],
       ['Spain', 38.0, 61000.0],
       ['Spain', 27.0, 48000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 35.0, 58000.0]], dtype=object)

In [ ]:
X_test[:,1:3]=imputer.transform(X_test[:,1:3])

In [ ]:
X_test

array([['Germany', 30.0, 54000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#strategy =mean,median,constant(fill_value=xxxx),most_frequent,

Categorical variables
1.Target variales

In [ ]:
#how to handle independent/input variables

In [ ]:
from sklearn.compose import ColumTransformer
from sklearn.

dummy encoding because of no order

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

creates object of column transofromer and give parameters

In [ ]:
ct=ColumnTransformer(transformers=[('encode',OneHotEncoder(),[0])],remainder='passthrough')

In [ ]:
X_train=ct.fit_transform(X_train)

In [ ]:
X_train

array([[0.0, 0.0, 1.0, 40.285714285714285, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 64714.28571428572],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [ ]:
X_test=ct.transform(X_test)

In [ ]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

dummy variable encoding

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder()

In [ ]:
x1=oe.fit_transform(X)#oder is associated with ordinal encoder but in nominal onehotecnder is only needed
x1

array([[ 0.,  6.,  6.],
       [ 2.,  0.,  0.],
       [ 1.,  1.,  2.],
       [ 2.,  4.,  4.],
       [ 1.,  5., nan],
       [ 0.,  2.,  3.],
       [ 2., nan,  1.],
       [ 0.,  7.,  7.],
       [ 1.,  8.,  8.],
       [ 0.,  3.,  5.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
y=le.fit_transform(y)

In [ ]:
y#0,1 values insted yes or no

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
ct1=ColumnTransformer(transformers=[('imputer1',SimpleImputer(strategy='mean'),[1,3])],remainder='passthrough')